export enum Routes {
  HOME = '/',
  ABOUT = '/about',
  CONTACT = '/contact',
  SIGN_UP = '/sign-up',
  SIGN_IN = '/sign-in',
  PROFILE = '/profile',
  PASSWORD_FORGET = '/pw-forget',
  ADMIN = '/admin',
  ADMIN_DETAILS = '/admin/:id',
  ACCOUNT = '/account',
  PASSWORD_CHANGE = '/pw-change',
  PASSWORD_RESET = '/pw-reset',
  NOT_FOUND = '/404',
  SERVER_ERROR = '/500',
  TERMS = '/terms',
  PRIVACY = '/privacy',
  COOKIES = '/cookies',
  ACCESSIBILITY = '/accessibility',
  SITEMAP = '/sitemap',
  FEEDBACK = '/feedback',
  HELP = '/help',
  FAQ = '/faq',
  LEGAL = '/legal',
}
